### ISSUE TITLE
Integrate main feature into vim-better-whitespace

### ISSUE THREAD

**Issue by alerque** [axelf4/vim-strip-trailing-whitespace#2]
I'm a long time user of [vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace) and ran across this plugin via ... no idea. Some Reddit thread about LSP I think.

The signature feature of only modifying otherwise editing lines is quite attractive to me and I would love that to be my default, but I don't want to give up the litany of other features found in that plugin, and they overlap so much that it does not seem smart to try to run both.

In an ideal world one plugin would have the best of both feature sets. Would you be willing to integrate this signature feature into that plugin? Or would you at least be willing to let the code be used under the terms of the Unlicense (as the other plugin uses that) instead of MIT so somebody could port it without creating a mixed license situation?

**Comment by alerque** [comment]
Never mind. The other plugin project already has a comparable feature.

```vim
let g:strip_only_modified_lines = 1
```

**Comment by axelf4** [comment]
Not too sure it would be a great idea. While I wrote this plugin because IMO tracking the lines with TWS is better than re-diffing the file on every save, it does lead different semantics: While much faster in the common case it does not handle `:%s/$/ /` too well. It also requires a relatively recent version of Vim for `listener_add()`. While I believe this is the plugin to use, nothing is without consequences and vim-better-whitespace might be a better default.
